core/urls.py
from django.contrib import admin
from django.urls import path

from vacancies.views import *

handler404 = custom_handler404
handler500 = custom_handler500
urlpatterns = [
    path("", MainView.as_view(), name="MainPage"),
    path("about/", About.as_view()),
    path("admin/", admin.site.urls),
    path("vacancies/", ListVacancies.as_view()),
    path("vacancies/<int:id>/", detail_vacancies),
    path("vacancies/cat/<title>/", VacancyBySpecialization.as_view()),
    path("companies/<int:id>/", DetailCompany.as_view()),
    path("mycompany/vacancies/", MyCompanyVacancyView.as_view()),
    path("mycompany/vacancies/create", create_my_vacancy),
    path("mycompany/vacancies/<int:vacancy_id>", update_my_vacancy),
    path("search/", SearchView),
    path("<token>/verify/", verify, name="verify"),
]

urlpatterns += [
    path("companies/", CompanyListView.as_view()),
    path("mycompany/", MyCompany, name="MyCompany"),
    path("profile", AccountSettings, name="profile"),
    path("logout", LogoutPage, name="logout"),
    path("login", LoginPage, name="login"),
    path("register/", RegisterPage, name="register"),
    path("myresume/", ResumeEdit, name="myresume"),
]

vacancies/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

User._meta.get_field("email")._unique = True
User._meta.get_field("email").blank = False
User._meta.get_field("email").null = False


class Company(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    logo = models.ImageField(default="company.png", null=True, blank=True)

    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    location = models.CharField(max_length=255, null=True)
    description = models.TextField(null=True, blank=True)
    employee_count = models.IntegerField(null=True, blank=True)

    external_site = models.ForeignKey(
        "SiteType", on_delete=models.SET_NULL, null=True, blank=True
    )
    external_logo_url = models.URLField(null=True, blank=True)
    external_url = models.URLField(null=True, blank=True)
    last_updated = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = ("external_site_id", "external_url")
        index_together = [["external_site_id", "last_updated"]]

    def __str__(self):
        return str(self.name)


class Specialty(models.Model):
    code = models.CharField(max_length=32)
    title = models.CharField(max_length=32, db_index=True)
    picture = models.ImageField(null=True, blank=True)

    def __str__(self):
        return str(self.code)


class Currency(models.Model):
    name = models.CharField(max_length=3, unique=True)

    def __str__(self):
        return str(self.name)


class SiteType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return str(self.name)


class Vacancy(models.Model):
    title = models.CharField(max_length=65535, db_index=True)
    is_internal = models.BooleanField(default=True)
    salary_min = models.PositiveIntegerField(null=True, blank=True)
    salary_max = models.PositiveIntegerField(null=True, blank=True)

    specialty = models.ForeignKey(
        Specialty,
        on_delete=models.CASCADE,
        related_name="vacancies",
        null=True,
        blank=True,
    )

    company = models.ForeignKey(
        Company,
        on_delete=models.CASCADE,
        related_name="vacancies",
        null=True,
        blank=True,
    )

    currency = models.ForeignKey(
        Currency,
        on_delete=models.CASCADE,
        related_name="vacancies",
        null=True,
        blank=True,
    )

    url = models.URLField(null=True, blank=True)

    site_type = models.ForeignKey(
        SiteType,
        on_delete=models.CASCADE,
        related_name="vacancies",
        null=True,
        blank=True,
    )
    vacancy_id = models.PositiveBigIntegerField(null=True, blank=True)
    hash = models.BinaryField(null=True, blank=True, max_length=16)

    address = models.CharField(null=True, blank=True, max_length=65535)
    experience = models.CharField(null=True, blank=True, max_length=255)
    skills = models.CharField(null=True, blank=True, max_length=65535, db_index=True)
    employment_mode = models.CharField(null=True, blank=True, max_length=255)
    description = models.TextField(null=True, blank=True)

    posted = models.DateField(null=True, blank=True)
    published_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        unique_together = ("site_type_id", "vacancy_id")


class Application(models.Model):
    written_username = models.CharField(max_length=32, null=True, blank=True)
    written_phone = models.CharField(max_length=32, null=True, blank=True)
    written_cover_letter = models.CharField(max_length=120, null=True, blank=True)
    vacancy = models.ForeignKey(
        Vacancy, on_delete=models.CASCADE, related_name="applications", null=True, blank=True
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="applications", null=True, blank=True
    )

    def __str__(self):
        return str(self.written_username)


class StatusModel(models.Model):
    title = models.CharField(max_length=32)

    def __str__(self):
        return str(self.title)


class GradeModel(models.Model):
    title = models.CharField(max_length=32)
    code = models.CharField(max_length=32)

    def __str__(self):
        return str(self.title)


class Resume(models.Model):
    verified = models.BooleanField(default=False)
    token = models.TextField(default="")
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default="check.png", null=True, blank=True)
    first_name = models.CharField(max_length=32, null=True, blank=True)
    last_name = models.CharField(max_length=32, null=True, blank=True)
    status = models.ForeignKey(
        StatusModel,
        on_delete=models.CASCADE,
        related_name="resume",
        null=True,
        blank=True,
    )
    salary = models.IntegerField(null=True, blank=True)
    specialty = models.ForeignKey(
        Specialty,
        on_delete=models.CASCADE,
        related_name="resume",
        null=True,
        blank=True,
    )
    currency = models.ForeignKey(
        Currency,
        on_delete=models.CASCADE,
        related_name="resumes",
        null=True,
        blank=True,
    )
    phone = models.CharField(max_length=32, null=True, blank=True)
    grade = models.ForeignKey(
        GradeModel,
        on_delete=models.CASCADE,
        related_name="resume",
        null=True,
        blank=True,
    )
    education = models.CharField(max_length=500, null=True, blank=True)
    experience = models.CharField(max_length=32, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    portfolio = models.CharField(max_length=32, null=True, blank=True)

    def __str__(self):
        return str(self.user.username)

vacancies/views.py
import logging

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.postgres.search import SearchVector
from django.db.models import Count
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, View

from core.base.list_filtered_mixin import ListFilteredMixin
from core.base.send_emails import send_verification_email_link, send_notification_link
from .filters import VacancyFilter
from .forms import *
from .models import Specialty, Application
from .token import account_activation_token

logger = logging.getLogger(__name__)


def SearchView(request):
    template_name = "search.html"
    q = request.GET.get("q", "")
    results = Vacancy.objects.all()
    if q:
        results = (
            Vacancy.objects.select_related("specialty", "company")
                .annotate(
                search=SearchVector("title") + SearchVector('specialty__title') +
                       SearchVector("company__name") + SearchVector("skills")
            ).filter(search__icontains=q)
        )
        return render(request, template_name, {"results": results, "query": q})
    return render(request, template_name, {"results": results})


class CompanyListView(ListView):
    model = Company
    paginate_by = 6
    template_name = "company_list.html"
    context_object_name = "objects"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_companies"] = Company.objects.all().count()
        return context


class About(View):
    def get(self, request):
        return render(request, "about.html")


def create_my_vacancy(request):
    form = VacancyForm()
    if request.method == "POST":
        form = VacancyForm(request.POST)
        if form.is_valid():
            Vacancy.objects.create(
                title=request.POST.get("title"),
                specialty_id=request.POST.get("specialty"),
                company=Company.objects.get(owner=request.user),
                skills=request.POST.get("skills"),
                is_internal=True,
                description=request.POST.get("description"),
                salary_min=request.POST.get("salary_min"),
                salary_max=request.POST.get("salary_max"),
            )
            return redirect("/mycompany/vacancies")
    context = {"form": form}
    return render(request, "vacancy-create.html", context=context)


def update_my_vacancy(request, vacancy_id):
    vacancy = Vacancy.objects.filter(id=vacancy_id).first()
    if vacancy == None:
        logger.warning("Запрос несуществующей вакансии!")
        raise Http404
    form = VacancyForm(instance=vacancy)
    if "update" in request.POST:
        form = VacancyForm(request.POST, instance=vacancy)
        if form.is_valid():
            messages.info(request, "Ваша вакансия обновлена!")
            form.save()
    elif "delete" in request.POST:
        vacancy = Vacancy.objects.get(id=vacancy_id)
        vacancy.delete()
        return redirect("/mycompany/vacancies")

    context = {
        "form": form,
        "applications": Vacancy.objects.get(id=vacancy_id).applications.all(),
    }
    return render(request, "vacancy-edit.html", context=context)


class MyCompanyVacancyView(ListView):
    template_name = "vacancy-list.html"
    context_object_name = "objects"
    paginate_by = 2

    def get_queryset(self):
        return Vacancy.objects.filter(company__owner=self.request.user)


def MyCompany(request):
    if not Company.objects.select_related("owner").filter(owner=request.user):
        if request.method == "POST":
            Company.objects.create(owner=request.user)
            return render(request, "company-edit.html")
        else:
            return render(request, "company-create.html")
    else:
        company = Company.objects.select_related("owner").get(owner=request.user)
        form = MyCompanyForm(instance=company)
        if request.method == "POST":
            form = MyCompanyForm(request.POST, request.FILES, instance=company)
            if form.is_valid():
                messages.info(request, "Информация о вашей компании успешно обновлена!")
                form.save()

        context = {"form": form, "logo": company.logo}
        return render(request, "company-edit.html", context)


def AccountSettings(request):
    user = request.user.resume
    form = ProfileForm(instance=user)
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()

    context = {"form": form}
    return render(request, "profile.html", context)


@login_required
def ResumeEdit(request):
    user = request.user.resume
    form = ResumeForm(instance=user)
    if request.method == "POST":
        form = ResumeForm(request.POST, instance=user)
        if form.is_valid():
            messages.info(request, "Ваше резюме обновлено!")
            form.save()

    context = {"form": form}
    return render(request, "resume-edit.html", context)


def RegisterPage(request):
    if request.user.is_authenticated:
        return redirect("/")
    else:
        form = CreateUserForm()
        if request.method == "POST":
            form = CreateUserForm(request.POST)
            if form.is_valid():
                user = form.save()
                username = form.cleaned_data.get("username")
                resume = Resume.objects.create(
                    user=user,
                    first_name=user.first_name,
                    last_name=user.last_name,
                    verified=False,
                    token=account_activation_token.make_token(user),
                )
                resume.save()
                send_verification_email_link(
                    to_email=user.email,
                    to_name=user.first_name,
                    link=f"http://localhost:8000/{user.resume.token}/verify/",
                    firstname=user.first_name,
                )
                messages.success(request, "Аккаунт был создан для " + username)
                return HttpResponseRedirect(reverse_lazy("login"))
        context = {"form": form}
        return render(request, "register.html", context)


def LoginPage(request):
    if request.user.is_authenticated:
        return redirect("/")
    else:
        if request.method == "POST":
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if not user.resume.verified:
                    messages.info(
                        request, "Ваш аккаунт не активирован, проверьте вашу почту !"
                    )
                    return render(request, "login.html")
                login(request, user=user)
                return HttpResponseRedirect(reverse_lazy("MainPage"))
            else:
                messages.info(request, "Неверный логин или пароль")

        context = {}
        return render(request, "login.html", context)


def LogoutPage(request):
    logout(request)
    return redirect("/")


class MyLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = "login.html"


class MyLogoutView(LogoutView):
    redirect_authenticated_user = False


class MySignupView(CreateView):
    form_class = UserCreationForm
    success_url = "login"
    template_name = "register.html"


class MainView(ListView):
    template_name = "index.html"
    model = Vacancy

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["objects"] = Specialty.objects.annotate(
            count=Count("vacancies")
        ).order_by("-count")
        context["companies"] = Company.objects.annotate(
            count=Count("vacancies")
        ).order_by("-count")
        return context


class ListVacancies(ListFilteredMixin, ListView):
    context_object_name = "objects"
    filter_set = VacancyFilter
    template_name = "vacancies.html"
    paginate_by = 12
    queryset = Vacancy.objects.order_by("-is_internal").select_related("company", "specialty", "currency").all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["total_vacancy"] = super().get_queryset().count()
        return context


    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     # filter = VacancyFilter(self.request.GET, queryset)
    #     return queryset

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     queryset = self.get_queryset()
    #     filter = VacancyFilter(self.request.GET, queryset)
    #     context["total_vacancy"] = queryset.count()
    #     context["objects"] = filter
    #     return context


class VacancyBySpecialization(ListView):
    template_name = "vacancies.html"
    paginate_by = 12
    queryset = Vacancy.objects.select_related("company", "specialty").order_by("id")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["objects"] = self.get_queryset().filter(
            specialty__code=self.kwargs["title"]
        )
        context["specialties"] = Specialty.objects.get(code=self.kwargs["title"])
        return context


class DetailCompany(ListView):
    model = Company
    paginate_by = 6
    context_object_name = "vacancies"
    template_name = "company.html"

    def get_queryset(self):
        return Vacancy.objects.select_related("company", "specialty").filter(
            company=get_object_or_404(

core/templates/about.html
<!DOCTYPE html>
<html lang="ru">
<style>
    html {
  height:100%;
}
    @import url("https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800,900");
body {

  margin:0;
}

.bg {
  animation:slide 3s ease-in-out infinite alternate;
  background-image: linear-gradient(-60deg, #6c3 50%, #09f 50%);
  bottom:0;
  left:-50%;
  opacity:.5;
  position:fixed;
  right:-50%;
  top:0;
  z-index:-1;
}

.bg2 {
  animation-direction:alternate-reverse;
  animation-duration:4s;
}

.bg3 {
  animation-duration:5s;
}

.content {
  background-color:rgba(255,255,255,.8);
  border-radius:.25em;
  box-shadow:0 0 .25em rgba(0,0,0,.25);
  box-sizing:border-box;
  left:50%;
  padding:10vmin;
  position:fixed;
  text-align:center;
  top:50%;
  transform:translate(-50%, -50%);
}

h1 {
}


@keyframes slide {
  0% {
    transform:translateX(-25%);
  }
  100% {
    transform:translateX(25%);
  }
}
</style>
<head>
  <meta charset="UTF-8">
  <title>Вакансии | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
    {% extends 'wrapper.html' %}
{% block container %}
    <main>
    <div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<div class="content">
  <h1>  Спроектировано и создано в образовательных целях</h1>
</div>
    </main>
{% endblock %}

core/templates/login.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>Вход</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>


<style>
    card {
        border-radius: 16px;
    }

    h1, p, a, label {
        color: #1b1e21;
    }

    body, html {
        background-color: #000;
        color: #fff;
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        overflow: hidden;
        position: fixed;
    }

    canvas {
        z-index: -1;
        position: absolute;
        top: 0;
        left: 0
    }
</style>
<style>
    .card {
        border-radius: 16px;
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js"
        integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>

{% extends 'wrapper.html' %}
{% block container %}
    <main class="container mt-5 ">
        <canvas id="bgCanvas"></canvas>
        <section data-aos="zoom-in" class="area col-8 col-lg-4 offset-2 offset-lg-4 card">
            <div class="row">
                <div class="mx-5">
                    <form class="form-signin pt-2 " method="post">
                        {% csrf_token %}
                        <div class="text-center mt-5 b-1">

                            <h1 class="h3 mb-3 font-weight-normal">Джуманджи</h1>
                            <p class="h5 font-weight-light">Войдите, чтобы управлять</p>
                        </div>
                        <div class="mt-5 form-label-group">
                            <input type="text" name="username" placeholder="Логин" maxlength="150" autofocus
                                   required
                                   id="id_username" class="form-control">
                            <label for="inputLogin"></label>
                        </div>
                        <div class="form-label-group ">

                            <input type="password" name="password" placeholder="Пароль" autocomplete="new-password"
                                   required id="id_password" class="form-control">
                            <label for="inputPassword"></label>
                        </div>
                        <div class="checkbox mb-3"></div>
                        <button class="btn btn-primary btn-lg btn-block" type="submit">Войти</button>
                    </form>
                    <div class="mt-4 text-center"><p>Нет аккаунта? <a href="/register">Зарегистрируйтесь!</a></p>
                    </div>
                    <div class="mt-4 text-center">
                        {% for message in messages %}
                            <p id="messages">{{ message }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

core/templates/profile.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <title>Редактировать профиль | Джуманджи</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,800,300" type="text/css" >
    <style>
    body {
      background-color: #F6F2E6;
    }
  </style>
</head>
{% extends 'wrapper.html' %}
{% block container %}
    <main data-aos="fade-zoom-in"
     data-aos-easing="ease-in-back"
     data-aos-delay="10"
     data-aos-offset="10" class="container mt-5">

    <section class="col-9 col-lg-4 offset-2 offset-lg-4 card">
      <div class="">
          <div class="text-center my-5 ">
            <h1 class="h3 mb-3 font-weight-normal">{{ request.user.first_name }} {{ request.user.last_name }}</h1>
          </div>
          <div class="text-center my-8">
            <img  class="rounded-circle shadow img center-block" src="{{request.user.resume.profile_pic.url}}" width="170" height="170">
          </div>
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="custom-file my-3">
                <input type="file" class="custom-file-input" accept="image/*" id="id_profile_pic" name="profile_pic">
                 <label class="custom-file-label" for="id_profile_pic">Сменить фото</label>
            </div>
            <div class="my-3 form-label-group">
            <p class="text-muted"> Телефон :
            <input type="text" name="phone" placeholder="Мобильный телефон" value="{{ form.phone.value|default_if_none:'' }}" autocomplete="new-password" required id="phone" class="form-control p-3"></p>
            <label for="inputPassword"></label>
            </div>

            <button class="btn btn-primary btn-lg btn-block my-3" type="submit" name="Update Information">Обновить информацию</button>
        </form>
      </div>
    </section>
    </main>
{% endblock %}

core/templates/resume-edit.html
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <title>Создать резюме | Джуманджи</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        body {
            background-color: #F6F2E6;
        }
    </style>
</head>

{% extends 'wrapper.html' %}
{% block container %}

    <main data-aos="zoom-out-down" class="container mt-3 pb-5">
        <section class="col-12 col-lg-6 offset-lg-3 mt-5 card">
            <div class="card-body px-3 pb-4">
                <h1 class="h4 pt-2 pb-3">Мое резюме</h1>
                {% for message in messages %}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endfor %}
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="form-group pb-2">
                                <label class="mb-2 text-dark" for="userName">Имя</label>
                                <input class="form-control" type="text" name="first_name"
                                       value="{{ form.first_name.value|default_if_none:'' }}" maxlength="32" required
                                       id="id_first_name">
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="form-group pb-2">
                                <label class="mb-2 text-dark" for="userSurname">Фамилия</label>
                                <input class="form-control" type="text" name="last_name"
                                       value="{{ form.last_name.value|default_if_none:'' }}" maxlength="32" required
                                       id="id_last_name">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-5">
                            <div class="form-group pb-2">
                                <label class="mb-2 text-dark" for="userReady">Готовность к работе</label>
                                <select class="custom-select mr-sm-2" id="status" name="status">
                                    {% for object in form.status %}
                                        <a>{{ object }}</a>
                                    {% endfor %}
                                </select>

                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="form-group pb-2">
                                <label class="mb-2 text-dark" for="userPortfolio">Вознаграждение</label>
                                <input class="form-control" type="number" name="salary"
                                       value="{{ form.salary.value|default_if_none:'' }}" required id="id_salary">
                            </div>
                        </div>
                        <div class="col-12 col-md-3">
                            <div class="form-group pb-2">
                                <label class="mb-2 text-dark" for="userSpecialization">Валюта</label>
                                <select class="custom-select mr-sm-2" id="currency" name="currency">
                                    {% for object in form.currency %}
                                        <a>{{ object }}</a>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 col-md-6">
                            <div class="form-group pb-2">
                                <label class="mb-2 text-dark" for="userSpecialization">Специализация</label>
                                <select class="custom-select mr-sm-2" id="specialty" name="specialty">
                                    {% for object in form.specialty %}
                                        <a>{{ object }}</a>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <div class="form-group pb-2">
                                <label class="mb-2 text-dark" for="userQualification">Квалификация</label>
                                <select class="custom-select mr-sm-2" id="grade" name="grade">
                                    {% for object in form.grade %}
                                        <a>{{ object }}</a>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group pb-2">
                        <label class="mb-2 text-dark" for="userEducation">Образование</label>
                        <textarea class="form-control text-uppercase" rows="4" name="education" id="education"
                                  style="color:#000;">{{ form.education.value|default_if_none:'' }}</textarea>
                    </div>
                    <div class="form-group pb-2">
                        <label class="mb-2 text-dark" for="userExperience">Опыт работы</label>
                        <textarea class="form-control" rows="4" name="experience" id="experience"
                                  style="color:#000;">{{ form.experience.value|default_if_none:'' }}</textarea>
                    </div>
                    <div class="form-group pb-3">
                        <label class="mb-2 text-dark" for="userPortfolio">Ссылка на портфолио</label>
                        <input class="form-control" type="text" placeholder="http://anylink.github.io" name="portfolio"
                               id="portfolio" value="{{ form.portfolio.value|default_if_none:'' }}">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-info" value="Сохранить">
                    </div>
                </form>
            </div>
        </section>
    </main>
{% endblock %}